"""baseline full schema

Revision ID: 9ecc074ef4bc
Revises: 
Create Date: 2026-06-10 15:47:46.615085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecc074ef4bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ROOT', 'ADMIN', 'OPERATOR', 'RESIDENT', 'SALES', 'GUARD', name='roleenum'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('avatar_path', sa.String(length=255), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), nullable=False),
    sa.Column('temp_password_plain', sa.String(length=128), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('access_gate_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('hint', sa.Enum('UNKNOWN', 'BLACKLIST', 'NO_PLATE', name='gate_hint'), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='access_direction_gate'), nullable=False),
    sa.Column('snapshot_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'HANDLED', 'DISMISSED', name='gate_status'), nullable=False),
    sa.Column('camera_id', sa.String(length=40), nullable=True),
    sa.Column('handled_by_guard_id', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_guard_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_blocks_name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('icon_color', sa.String(length=50), nullable=False),
    sa.Column('target_blocks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_reason', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_push_device_tokens_token_hash')
    )
    op.create_table('qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token', name='uq_qr_tokens_token')
    )
    op.create_table('sales_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_type', sa.Enum('FULL', 'INSTALLMENT', name='sales_contract_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'VIEWED', 'APPROVED', 'REJECTED', 'PRINTED', name='sales_contract_status'), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('contract_year', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('buyer_full_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_id_series', sa.String(length=20), nullable=True),
    sa.Column('buyer_id_number', sa.String(length=50), nullable=True),
    sa.Column('buyer_fin', sa.String(length=30), nullable=True),
    sa.Column('buyer_phone', sa.String(length=50), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.Column('buyer_address', sa.Text(), nullable=True),
    sa.Column('house_number', sa.String(length=50), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_per_m2_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_price_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('initial_payment_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('remaining_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('months_count', sa.Integer(), nullable=True),
    sa.Column('monthly_payment_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approval_requested_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_by_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.Column('printed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['viewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=256), nullable=False),
    sa.Column('masked_pan', sa.String(length=32), nullable=False),
    sa.Column('card_brand', sa.String(length=32), nullable=True),
    sa.Column('expiry_month', sa.Integer(), nullable=True),
    sa.Column('expiry_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token_id', name='uq_saved_cards_user_token')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('meter_type', sa.Enum('ELECTRIC', 'GAS', 'WATER', 'SEWERAGE', 'SERVICE', 'RENT', 'CONSTRUCTION', name='metertype'), nullable=False),
    sa.Column('customer_type', sa.Enum('INDIVIDUAL', 'LEGAL', name='customertype'), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.Column('use_multiplier', sa.Boolean(), nullable=False),
    sa.Column('consumption_multiplier', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stable_tariff', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sewerage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'meter_type', 'customer_type', name='uq_tariffs_name_scope')
    )
    op.create_table('residents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('resident_type', sa.Enum('OWNER', 'TENANT', 'SUBTENANT', 'OFFICE', name='residenttype'), nullable=False),
    sa.Column('customer_type', sa.Enum('INDIVIDUAL', 'LEGAL', name='customertype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='residentstatus'), nullable=False),
    sa.Column('owner_full_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=50), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'unit_number', name='uq_resident_block_unit')
    )
    op.create_table('sales_contract_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('month_no', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['sales_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('from_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('to_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='access_direction_req'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'HANDLED', 'REJECTED', name='request_status'), nullable=False),
    sa.Column('handled_by_guard_id', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handled_by_guard_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('RESIDENT', 'GUEST', name='vehicle_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLACKLIST', 'EXPIRED', name='vehicle_status'), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_vehicles_plate'), 'access_vehicles', ['plate'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIAL', 'PAID', 'OVERPAID', 'CANCELED', name='invoice_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_invoices_number'),
    sa.UniqueConstraint('resident_id', 'period_year', 'period_month', name='uq_invoice_resident_period')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', name='notification_status'), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('appeal_workflow', sa.String(length=40), nullable=True),
    sa.Column('staff_message', sa.Text(), nullable=True),
    sa.Column('workflow_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'ONLINE', 'ADVANCE', name='payment_method'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('meter_type', sa.Enum('ELECTRIC', 'GAS', 'WATER', 'SEWERAGE', 'SERVICE', 'RENT', 'CONSTRUCTION', name='metertype'), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('initial_reading', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resident_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_residents',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resident_id')
    )
    op.create_table('access_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='access_direction_evt'), nullable=False),
    sa.Column('decision', sa.Enum('AUTO_OPEN', 'MANUAL_OPEN', 'DENIED', 'BLACKLIST_ALERT', name='event_decision'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'REQUEST', 'CAMERA', name='event_source'), nullable=False),
    sa.Column('matched_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('guard_id', sa.Integer(), nullable=True),
    sa.Column('visitor_name', sa.String(length=200), nullable=True),
    sa.Column('visitor_doc_id', sa.String(length=40), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=True),
    sa.Column('snapshot_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('exit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_vehicle_id'], ['access_vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_events_plate'), 'access_events', ['plate'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resident_meter_id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_percent', sa.Integer(), nullable=False),
    sa.Column('amount_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stable_fee_net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('stable_fee_vat', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('stable_fee_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_meter_id'], ['resident_meters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('trtype', sa.String(length=8), nullable=True),
    sa.Column('rrn', sa.String(length=32), nullable=True),
    sa.Column('int_ref', sa.String(length=64), nullable=True),
    sa.Column('approval', sa.String(length=32), nullable=True),
    sa.Column('action_code', sa.String(length=16), nullable=True),
    sa.Column('rc', sa.String(length=16), nullable=True),
    sa.Column('gateway_status', sa.String(length=32), nullable=False),
    sa.Column('terminal_category', sa.String(length=32), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('callback_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_online_transactions_order_id')
    )
    op.create_index(op.f('ix_online_transactions_order_id'), 'online_transactions', ['order_id'], unique=False)
    op.create_table('payment_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.Column('resident_meter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resident_meter_id'], ['resident_meters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('meter_reading_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount_net', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meter_reading_id'], ['meter_readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_reading_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_reading_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meter_reading_id'], ['meter_readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_reading_id', name='uq_meter_reading_photos_reading_id')
    )
    op.create_table('payment_application_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['payment_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_application_lines')
    op.drop_table('meter_reading_photos')
    op.drop_table('invoice_lines')
    op.drop_table('reading_logs')
    op.drop_table('payment_logs')
    op.drop_table('payment_applications')
    op.drop_index(op.f('ix_online_transactions_order_id'), table_name='online_transactions')
    op.drop_table('online_transactions')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_access_events_plate'), table_name='access_events')
    op.drop_table('access_events')
    op.drop_table('user_residents')
    op.drop_table('resident_services')
    op.drop_table('resident_meters')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_access_vehicles_plate'), table_name='access_vehicles')
    op.drop_table('access_vehicles')
    op.drop_table('access_requests')
    op.drop_table('tariff_steps')
    op.drop_table('sales_contract_installments')
    op.drop_table('residents')
    op.drop_table('tariffs')
    op.drop_table('saved_cards')
    op.drop_table('sales_contracts')
    op.drop_table('qr_tokens')
    op.drop_table('push_device_tokens')
    op.drop_table('news')
    op.drop_table('blocks')
    op.drop_table('access_gate_events')
    op.drop_table('users')
    # ### end Alembic commands ###
